# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-paypal}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Kopf","Bob Van Landuyt"]
  s.date = %q{2022-06-11}
  s.description = %q{Wrapper for the paypal-API}
  s.email = %q{rubypaypal@ryankopf.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "lib/ruby-paypal.rb",
    "lib/ruby-paypal/credit_card_checks.rb",
    "lib/ruby-paypal/paypal.rb",
    "test/ts_ruby-paypal.rb"
  ]
  s.homepage = %q{http://github.com/ryankopf/ruby-paypal}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Wrapper for the paypal-API}

  s.add_development_dependency(%q<shoulda>, [">= 0"])
  s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.6.3"])
  s.add_development_dependency(%q<rcov>, [">= 0"])

end

